spring:
  application:
    name: snippet-service

  datasource:
    url: jdbc:postgresql://postgres_db:5432/snippet-serviceDB
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  asset:
    service:
      url: http://asset-service:8080/v1/asset
  authorization:
    service:
      url: http://authorization-service:8080/api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI:}
          client-id: ${AUTH_CLIENT_ID:}
          client-secret: ${AUTH_CLIENT_SECRET:}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

stream:
  runner:
    key: runnerStream

# Configuración de Auth0
auth0:
  audience: ${AUTH0_AUDIENCE:}
